# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app\view\uis\sort.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SortInterface(object):
    def setupUi(self, SortInterface):
        SortInterface.setObjectName("SortInterface")
        SortInterface.resize(1000, 700)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SortInterface)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.useFiltersToggle = SwitchButton(SortInterface)
        self.useFiltersToggle.setText("")
        self.useFiltersToggle.setObjectName("useFiltersToggle")
        self.horizontalLayout.addWidget(self.useFiltersToggle, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.sortTextInput = PlainTextEdit(SortInterface)
        self.sortTextInput.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.sortTextInput.setObjectName("sortTextInput")
        self.verticalLayout.addWidget(self.sortTextInput)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sortBtn = PushButton(SortInterface)
        self.sortBtn.setObjectName("sortBtn")
        self.horizontalLayout_2.addWidget(self.sortBtn, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.sortedOutput = PlainTextEdit(SortInterface)
        self.sortedOutput.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.sortedOutput.setObjectName("sortedOutput")
        self.verticalLayout.addWidget(self.sortedOutput)
        self.copySortedBtn = PushButton(SortInterface)
        self.copySortedBtn.setObjectName("copySortedBtn")
        self.verticalLayout.addWidget(self.copySortedBtn, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(SortInterface)
        QtCore.QMetaObject.connectSlotsByName(SortInterface)

    def retranslateUi(self, SortInterface):
        _translate = QtCore.QCoreApplication.translate
        SortInterface.setWindowTitle(_translate("SortInterface", "Form"))
        self.sortTextInput.setPlaceholderText(_translate("SortInterface", "Input"))
        self.sortBtn.setText(_translate("SortInterface", "Sort"))
        self.sortedOutput.setPlaceholderText(_translate("SortInterface", "Output"))
        self.copySortedBtn.setText(_translate("SortInterface", "Copy"))
from qfluentwidgets import PlainTextEdit, PushButton, SwitchButton


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SortInterface = QtWidgets.QWidget()
    ui = Ui_SortInterface()
    ui.setupUi(SortInterface)
    SortInterface.show()
    sys.exit(app.exec_())
