# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/view/uis/excel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExcelInterface(object):
    def setupUi(self, ExcelInterface):
        ExcelInterface.setObjectName("ExcelInterface")
        ExcelInterface.resize(1000, 700)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ExcelInterface)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.websiteNameCombo = ComboBox(ExcelInterface)
        self.websiteNameCombo.setObjectName("websiteNameCombo")
        self.websiteNameCombo.addItem("")
        self.websiteNameCombo.addItem("")
        self.websiteNameCombo.addItem("")
        self.horizontalLayout.addWidget(self.websiteNameCombo, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.goToSetUpBtn = PushButton(ExcelInterface)
        self.goToSetUpBtn.setObjectName("goToSetUpBtn")
        self.horizontalLayout.addWidget(self.goToSetUpBtn, 0, QtCore.Qt.AlignLeft)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.inputFileCard = QtWidgets.QVBoxLayout()
        self.inputFileCard.setObjectName("inputFileCard")
        self.verticalLayout.addLayout(self.inputFileCard)
        self.tablePreview = TableWidget(ExcelInterface)
        self.tablePreview.setObjectName("tablePreview")
        self.tablePreview.setColumnCount(0)
        self.tablePreview.setRowCount(0)
        self.verticalLayout.addWidget(self.tablePreview)
        self.excelRunBtn = PushButton(ExcelInterface)
        self.excelRunBtn.setObjectName("excelRunBtn")
        self.verticalLayout.addWidget(self.excelRunBtn, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ExcelInterface)
        QtCore.QMetaObject.connectSlotsByName(ExcelInterface)

    def retranslateUi(self, ExcelInterface):
        _translate = QtCore.QCoreApplication.translate
        ExcelInterface.setWindowTitle(_translate("ExcelInterface", "Form"))
        self.websiteNameCombo.setItemText(0, _translate("ExcelInterface", "Saks85"))
        self.websiteNameCombo.setItemText(1, _translate("ExcelInterface", "Saucony"))
        self.websiteNameCombo.setItemText(2, _translate("ExcelInterface", "Arena"))
        self.goToSetUpBtn.setText(_translate("ExcelInterface", "Go To Set Up"))
        self.excelRunBtn.setText(_translate("ExcelInterface", "Parse"))
from qfluentwidgets import ComboBox, PushButton, TableWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExcelInterface = QtWidgets.QWidget()
    ui = Ui_ExcelInterface()
    ui.setupUi(ExcelInterface)
    ExcelInterface.show()
    sys.exit(app.exec_())
