# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/view/uis/setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetUpInterface(object):
    def setupUi(self, SetUpInterface):
        SetUpInterface.setObjectName("SetUpInterface")
        SetUpInterface.resize(1000, 700)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(SetUpInterface)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.presetNameEdit = LineEdit(SetUpInterface)
        self.presetNameEdit.setObjectName("presetNameEdit")
        self.horizontalLayout_3.addWidget(self.presetNameEdit)
        self.delPresetBtn = ToolButton(SetUpInterface)
        self.delPresetBtn.setText("")
        self.delPresetBtn.setObjectName("delPresetBtn")
        self.horizontalLayout_3.addWidget(self.delPresetBtn)
        self.addPresetBtn = ToolButton(SetUpInterface)
        self.addPresetBtn.setText("")
        self.addPresetBtn.setObjectName("addPresetBtn")
        self.horizontalLayout_3.addWidget(self.addPresetBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.presetList = ListView(SetUpInterface)
        self.presetList.setMaximumSize(QtCore.QSize(16777215, 130))
        self.presetList.setObjectName("presetList")
        self.verticalLayout_2.addWidget(self.presetList, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filtersEdit = PlainTextEdit(SetUpInterface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtersEdit.sizePolicy().hasHeightForWidth())
        self.filtersEdit.setSizePolicy(sizePolicy)
        self.filtersEdit.setObjectName("filtersEdit")
        self.horizontalLayout.addWidget(self.filtersEdit)
        self.orderEdit = PlainTextEdit(SetUpInterface)
        self.orderEdit.setObjectName("orderEdit")
        self.horizontalLayout.addWidget(self.orderEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.savePresetBtn = PushButton(SetUpInterface)
        self.savePresetBtn.setObjectName("savePresetBtn")
        self.horizontalLayout_2.addWidget(self.savePresetBtn, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(SetUpInterface)
        QtCore.QMetaObject.connectSlotsByName(SetUpInterface)

    def retranslateUi(self, SetUpInterface):
        _translate = QtCore.QCoreApplication.translate
        SetUpInterface.setWindowTitle(_translate("SetUpInterface", "Form"))
        self.filtersEdit.setPlaceholderText(_translate("SetUpInterface", "Filters"))
        self.orderEdit.setPlaceholderText(_translate("SetUpInterface", "Order"))
        self.savePresetBtn.setText(_translate("SetUpInterface", "Save"))
from qfluentwidgets import LineEdit, ListView, PlainTextEdit, PushButton, ToolButton


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SetUpInterface = QtWidgets.QWidget()
    ui = Ui_SetUpInterface()
    ui.setupUi(SetUpInterface)
    SetUpInterface.show()
    sys.exit(app.exec_())
