# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app\view\uis\get_links.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GetLinksInterface(object):
    def setupUi(self, GetLinksInterface):
        GetLinksInterface.setObjectName("GetLinksInterface")
        GetLinksInterface.resize(1000, 700)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GetLinksInterface)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.websiteNameCombo = ComboBox(GetLinksInterface)
        self.websiteNameCombo.setObjectName("websiteNameCombo")
        self.horizontalLayout.addWidget(self.websiteNameCombo)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.inputFileCard = QtWidgets.QVBoxLayout()
        self.inputFileCard.setObjectName("inputFileCard")
        self.verticalLayout.addLayout(self.inputFileCard)
        self.tablePreview = CustomTable(GetLinksInterface)
        self.tablePreview.setObjectName("tablePreview")
        self.tablePreview.setColumnCount(0)
        self.tablePreview.setRowCount(0)
        self.verticalLayout.addWidget(self.tablePreview)
        self.sheetsView = SmoothScrollArea(GetLinksInterface)
        self.sheetsView.setMaximumSize(QtCore.QSize(16777215, 40))
        self.sheetsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sheetsView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.sheetsView.setWidgetResizable(True)
        self.sheetsView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.sheetsView.setObjectName("sheetsView")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 988, 38))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sheetsView.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.sheetsView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.excelRunBtn = PushButton(GetLinksInterface)
        self.excelRunBtn.setMinimumSize(QtCore.QSize(110, 0))
        self.excelRunBtn.setObjectName("excelRunBtn")
        self.horizontalLayout_2.addWidget(self.excelRunBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.progressBar = ProgressBar(GetLinksInterface)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(GetLinksInterface)
        QtCore.QMetaObject.connectSlotsByName(GetLinksInterface)

    def retranslateUi(self, GetLinksInterface):
        _translate = QtCore.QCoreApplication.translate
        GetLinksInterface.setWindowTitle(_translate("GetLinksInterface", "Form"))
        self.excelRunBtn.setText(_translate("GetLinksInterface", "Get Links"))
from app.components.custom_table import CustomTable
from qfluentwidgets import ComboBox, ProgressBar, PushButton, SmoothScrollArea


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GetLinksInterface = QtWidgets.QWidget()
    ui = Ui_GetLinksInterface()
    ui.setupUi(GetLinksInterface)
    GetLinksInterface.show()
    sys.exit(app.exec_())
